#!/bin/bash


if [ ! -v aolconfFLAG ]; then
echo "ERROR: This script should be called from aolconf main script"
exit
fi





function initDMfunc {
    aoconflog "start initDM ${DMindex}"
    file="./conf/conf_dm${DMindex}xsize.txt"
    if [ -a $file ]
        then
        dmxsize=$(echo "$(cat $file)")
        else
        dmxsize=32 #default
        fi
    file="./conf/conf_dm${DMindex}ysize.txt"
    if [ -a $file ]
         then          
         dmysize=$(echo "$(cat $file)")
         else
         dmysize=32 #default
         fi

    echo "dm2dm_mode = $dm2dm_mode"
    if [ ! "$dm2dm_mode" = "1" ];
    then
    dmmodes="empty"
    dm2dmO="empty"
    dm2dmM="empty"
    fi
    echo "dmwfsrefmode = $dmwfsrefmode"
    if [ ! "$dmwfsrefmode" = "1" ];
    then
    dmwrefRM="empty"
    dmwrefO="empty"
    fi


# start main DM channels
    tmuxname="aol${LOOPNUMBER}dm${DMindex}comb"
    echo "tmux session :  $tmuxname"
    sleep 1
    tmux kill-session -t $tmuxname
    tmux new-session -d -s $tmuxname
    tmux send-keys -t $tmuxname "$execname -n aol${LOOPNUMBER}dm${DMindex}comb" C-m
    if [ "$CPUconfRT" -eq "1" ]; then
    tmux send-keys -t $tmuxname "csetpmove system" C-m
    fi
    if [ "$dmvoltmode" = "1" ]; then 
    tmux send-keys -t $tmuxname "readshmim dmvolt" C-m
    fi
    if [ "$dm2dm_mode" = "1" ]; then
    tmux send-keys -t $tmuxname "readshmim ${dm2dmM}" C-m
    tmux send-keys -t $tmuxname "readshmim ${dm2dmO}" C-m
    fi
    if [ "${dmwfsrefmode}" = "1" ]; then
    tmux send-keys -t $tmuxname "readshmim ${dmwrefRM}" C-m
    tmux send-keys -t $tmuxname "readshmim ${dmwrefO}" C-m
    fi

    

    echo "aolcontrolDMcomb ${DMindex} ${dmxsize} ${dmysize} 8 ${dmcombavemode} $dm2dm_mode ${dm2dmM} ${dm2dmO} ${dmwfsrefmode} ${dmwrefRM} ${dmwrefO} ${dmvoltmode} dmvolt 0.0 120.0" > cmd00.txt
    echo "$tmuxname" >> cmd00.txt
    echo "dm2dm_mode : $dm2dm_mode" >> cmd00.txt
    echo "dm2dmM : $dm2dmM" >> cmd00.txt
    echo "dm2dmO : $dm2dmO" >> cmd00.txt
    echo "dmvoltmode : $dmvoltmode" >> cmd00.txt
    
    aoconflog "STARTING DM COM"
    tmux send-keys -t $tmuxname "aolcontrolDMcomb ${DMindex} ${dmxsize} ${dmysize} 12 ${dmcombavemode} $dm2dm_mode ${dm2dmM} ${dm2dmO} ${dmwfsrefmode} ${dmwrefRM} ${dmwrefO} ${dmvoltmode} dmvolt 0.0 120.0" C-m
}


function stopDMfunc {
    aoconflog "stop initDM ${DMindex}"
    tmuxname="aol${LOOPNUMBER}dm${DMindex}comboff"
    tmux kill-session -t $tmuxname
    tmux new-session -d -s $tmuxname
    tmux send-keys -t $tmuxname "$execname -n aol${LOOPNUMBER}dm${DMindex}comboff" C-m
    tmux send-keys -t $tmuxname "aoloopcontroldmcomboff ${DMindex}" C-m
    tmux send-keys -t $tmuxname "exit" C-m
    tmux send-keys -t $tmuxname "exit" C-m
#    tmux kill-session -t $tmuxname # not necessary - just making sure
    tmuxname="aol${LOOPNUMBER}dm${DMindex}comb"
    tmux send-keys -t $tmuxname "exit" C-m
    tmux send-keys -t $tmuxname "exit" C-m
#    tmux kill-session -t $tmuxname # not necessary - just making sure
}



