#!/bin/bash


if [ ! -v aolconfFLAG ]; then
echo "ERROR: This script should be called from aolconf main script"
exit
fi



function startstreamlog {
aoconflog "log $1 ON"
echo "1" > ./status/stat_log$1.txt
tmuxnameC="logC_$1"
tmux new-session -d -s $tmuxnameC
savedir=$(cat ./conf/conf_savedir_name.txt)
datestr=`date -u +%Y%m%d`
mkdir -p $savedir/$datestr/$1/
tmux send-keys -t $tmuxnameC "logshim -c aol${LOOPNUMBER}log $1 30000 $savedir/$datestr/$1/" C-m
tmuxname="log_$1"
tmux new-session -d -s $tmuxname
tmux send-keys -t $tmuxname "logshimon $1" C-m
}

function stopstreamlog {
aoconflog "log $1 OFF"
echo "0" > ./status/stat_log$1.txt
tmuxname="log_$1"
tmux new-session -d -s $tmuxname
tmux send-keys -t $tmuxname "logshimoff $1" C-m
echo "0" > ./status/stat_log$1.txt
}


function killstreamlog {
aoconflog "log $1 KILL"
echo "0" > ./status/stat_log$1.txt
tmuxname="log_$1"
tmux new-session -d -s $tmuxname
tmux send-keys -t $tmuxname "logshimkill $1" C-m
tmux kill-session -t $tmuxname
tmuxnameC="logC_$1"
tmux kill-session -t $tmuxnameC
echo "0" > ./status/stat_log$1.txt
}


function start_Telemetrylog_all {

aoconflog "start ALL telemetry logging"

startstreamlog aol${LOOPNUMBER}_wfsim
echo "1" > "./status/stat_log_aol${LOOPNUMBER}_wfsim.txt"

startstreamlog aol${LOOPNUMBER}_wfsref0
echo "1" > "./status/stat_log_aol${LOOPNUMBER}_wfsref0.txt"

startstreamlog aol${LOOPNUMBER}_wfsref
echo "1" > "./status/stat_log_aol${LOOPNUMBER}_wfsref.txt"


startstreamlog aol${LOOPNUMBER}_gainb
echo "1" > "./status/stat_log_aol${LOOPNUMBER}_gainb.txt"

startstreamlog aol${LOOPNUMBER}_DMmode_GAIN
echo "1" > "./status/stat_log_aol${LOOPNUMBER}_DMmode_GAIN.txt"

startstreamlog aol${LOOPNUMBER}_DMmode_LIMIT
echo "1" > "./status/stat_log_aol${LOOPNUMBER}_DMmode_LIMIT.txt"

startstreamlog aol${LOOPNUMBER}_multfb
echo "1" > "./status/stat_log_aol${LOOPNUMBER}_multfb.txt"

startstreamlog aol${LOOPNUMBER}_DMmode_MULTF
echo "1" > "./status/stat_log_aol${LOOPNUMBER}_DMmode_MULTF.txt"



startstreamlog dm${DMindex}disp
echo "1" > "./status/stat_log_dm${DMindex}disp.txt"

startstreamlog dm${DMindex}disp00
echo "1" > "./status/stat_log_dm${DMindex}disp00.txt"

startstreamlog dm${DMindex}disp01
echo "1" > "./status/stat_log_dm${DMindex}disp01.txt"

startstreamlog dm${DMindex}disp02
echo "1" > "./status/stat_log_dm${DMindex}disp02.txt"

startstreamlog dm${DMindex}disp03
echo "1" > "./status/stat_log_dm${DMindex}disp03.txt"

startstreamlog dm${DMindex}disp04
echo "1" > "./status/stat_log_dm${DMindex}disp04.txt"

startstreamlog dm${DMindex}disp05
echo "1" > "./status/stat_log_dm${DMindex}disp05.txt"

startstreamlog dm${DMindex}disp06
echo "1" > "./status/stat_log_dm${DMindex}disp06.txt"

startstreamlog dm${DMindex}disp07
echo "1" > "./status/stat_log_dm${DMindex}disp07.txt"

startstreamlog dm${DMindex}disp08
echo "1" > "./status/stat_log_dm${DMindex}disp08.txt"

startstreamlog dm${DMindex}disp09
echo "1" > "./status/stat_log_dm${DMindex}disp09.txt"

startstreamlog dm${DMindex}disp10
echo "1" > "./status/stat_log_dm${DMindex}disp10.txt"

startstreamlog dm${DMindex}disp11
echo "1" > "./status/stat_log_dm${DMindex}disp11.txt"


if [ "${dm2dm_mode}" = "0" ];
then

startstreamlog aol${LOOPNUMBER}_modeval
echo "1" > "./status/stat_log_modeval.txt"

startstreamlog aol${LOOPNUMBER}_modeval_dm_now
echo "1" > "./status/stat_log_modeval_dm_now.txt"

startstreamlog aol${LOOPNUMBER}_modeval_dm_now_filt
echo "1" > "./status/stat_log_modeval_dm_now_filt.txt"

startstreamlog aol${LOOPNUMBER}_modeval_ol
echo "1" > "./status/stat_log_modeval_ol.txt"

fi
}


function stop_Telemetrylog_all {
aoconflog "stop ALL telemetry logging"

stopstreamlog aol${LOOPNUMBER}_wfsim
echo "0" > "./status/stat_log_aol${LOOPNUMBER}_wfsim.txt"

stopstreamlog aol${LOOPNUMBER}_wfsref0
echo "0" > "./status/stat_log_aol${LOOPNUMBER}_wfsref0.txt"

stopstreamlog aol${LOOPNUMBER}_wfsref
echo "0" > "./status/stat_log_aol${LOOPNUMBER}_wfsref.txt"


stopstreamlog aol${LOOPNUMBER}_gainb
echo "0" > "./status/stat_log_aol${LOOPNUMBER}_gainb.txt"

stopstreamlog aol${LOOPNUMBER}_DMmode_GAIN
echo "0" > "./status/stat_log_aol${LOOPNUMBER}_DMmode_GAIN.txt"

stopstreamlog aol${LOOPNUMBER}_DMmode_LIMIT
echo "0" > "./status/stat_log_aol${LOOPNUMBER}_DMmode_LIMIT.txt"

stopstreamlog aol${LOOPNUMBER}_multfb
echo "0" > "./status/stat_log_aol${LOOPNUMBER}_multfb.txt"

stopstreamlog aol${LOOPNUMBER}_DMmode_MULTF
echo "0" > "./status/stat_log_aol${LOOPNUMBER}_DMmode_MULTF.txt"


stopstreamlog dm${DMindex}disp
echo "0" > "./status/stat_log_dm${DMindex}disp.txt"

stopstreamlog dm${DMindex}disp00
echo "0" > "./status/stat_log_dm${DMindex}disp00.txt"

stopstreamlog dm${DMindex}disp01
echo "0" > "./status/stat_log_dm${DMindex}disp01.txt"

stopstreamlog dm${DMindex}disp02
echo "0" > "./status/stat_log_dm${DMindex}disp02.txt"

stopstreamlog dm${DMindex}disp03
echo "0" > "./status/stat_log_dm${DMindex}disp03.txt"

stopstreamlog dm${DMindex}disp04
echo "0" > "./status/stat_log_dm${DMindex}disp04.txt"

stopstreamlog dm${DMindex}disp05
echo "0" > "./status/stat_log_dm${DMindex}disp05.txt"

stopstreamlog dm${DMindex}disp06
echo "0" > "./status/stat_log_dm${DMindex}disp06.txt"

stopstreamlog dm${DMindex}disp07
echo "0" > "./status/stat_log_dm${DMindex}disp07.txt"

stopstreamlog dm${DMindex}disp08
echo "0" > "./status/stat_log_dm${DMindex}disp08.txt"

stopstreamlog dm${DMindex}disp09
echo "0" > "./status/stat_log_dm${DMindex}disp09.txt"

stopstreamlog dm${DMindex}disp10
echo "0" > "./status/stat_log_dm${DMindex}disp10.txt"

stopstreamlog dm${DMindex}disp11
echo "0" > "./status/stat_log_dm${DMindex}disp11.txt"

log "stop ALL telemetry logging"

if [ "${dm2dm_mode}" = "0" ];
then

stopstreamlog aol${LOOPNUMBER}_modeval
echo "0" > "./status/stat_log_modeval.txt"

stopstreamlog aol${LOOPNUMBER}_modeval_dm_now
echo "0" > "./status/stat_log_modeval_dm_now.txt"

stopstreamlog aol${LOOPNUMBER}_modeval_dm_now_filt
echo "0" > "./status/stat_log_modeval_dm_now_filt.txt"

stopstreamlog aol${LOOPNUMBER}_modeval_ol
echo "0" > "./status/stat_log_modeval_ol.txt"

fi
}


function kill_Telemetrylog_all {
aoconflog "kill ALL telemetry logging"

killstreamlog aol${LOOPNUMBER}_wfsim
echo "0" > "./status/stat_log_aol${LOOPNUMBER}_wfsim.txt"

killstreamlog aol${LOOPNUMBER}_wfsref0
echo "0" > "./status/stat_log_aol${LOOPNUMBER}_wfsref0.txt"

killstreamlog aol${LOOPNUMBER}_wfsref
echo "0" > "./status/stat_log_aol${LOOPNUMBER}_wfsref.txt"


killstreamlog aol${LOOPNUMBER}_gainb
echo "0" > "./status/stat_log_aol${LOOPNUMBER}_gainb.txt"

killstreamlog aol${LOOPNUMBER}_DMmode_GAIN
echo "0" > "./status/stat_log_aol${LOOPNUMBER}_DMmode_GAIN.txt"

killstreamlog aol${LOOPNUMBER}_DMmode_LIMIT
echo "0" > "./status/stat_log_aol${LOOPNUMBER}_DMmode_LIMIT.txt"

killstreamlog aol${LOOPNUMBER}_multfb
echo "0" > "./status/stat_log_aol${LOOPNUMBER}_multfb.txt"

killstreamlog aol${LOOPNUMBER}_DMmode_MULTF
echo "0" > "./status/stat_log_aol${LOOPNUMBER}_DMmode_MULTF.txt"


killstreamlog dm${DMindex}disp
echo "0" > "./status/stat_log_dm${DMindex}disp.txt"

killstreamlog dm${DMindex}disp00
echo "0" > "./status/stat_log_dm${DMindex}disp00.txt"

killstreamlog dm${DMindex}disp01
echo "0" > "./status/stat_log_dm${DMindex}disp01.txt"

killstreamlog dm${DMindex}disp02
echo "0" > "./status/stat_log_dm${DMindex}disp02.txt"

killstreamlog dm${DMindex}disp03
echo "0" > "./status/stat_log_dm${DMindex}disp03.txt"

killstreamlog dm${DMindex}disp04
echo "0" > "./status/stat_log_dm${DMindex}disp04.txt"

killstreamlog dm${DMindex}disp05
echo "0" > "./status/stat_log_dm${DMindex}disp05.txt"

killstreamlog dm${DMindex}disp06
echo "0" > "./status/stat_log_dm${DMindex}disp06.txt"

killstreamlog dm${DMindex}disp07
echo "0" > "./status/stat_log_dm${DMindex}disp07.txt"

killstreamlog dm${DMindex}disp08
echo "0" > "./status/stat_log_dm${DMindex}disp08.txt"

killstreamlog dm${DMindex}disp09
echo "0" > "./status/stat_log_dm${DMindex}disp09.txt"

killstreamlog dm${DMindex}disp10
echo "0" > "./status/stat_log_dm${DMindex}disp10.txt"

killstreamlog dm${DMindex}disp11
echo "0" > "./status/stat_log_dm${DMindex}disp11.txt"

log "kill ALL telemetry logging"

if [ "${dm2dm_mode}" = "0" ];
then

killstreamlog aol${LOOPNUMBER}_modeval
echo "0" > "./status/stat_log_modeval.txt"

killstreamlog aol${LOOPNUMBER}_modeval_dm_now
echo "0" > "./status/stat_log_modeval_dm_now.txt"

killstreamlog aol${LOOPNUMBER}_modeval_dm_now_filt
echo "0" > "./status/stat_log_modeval_dm_now_filt.txt"

killstreamlog aol${LOOPNUMBER}_modeval_ol
echo "0" > "./status/stat_log_modeval_ol.txt"

fi
}




