#! /bin/bash




NBARGS=0
pname=`echo "$0" | sed "s/\.\///g"`

function printHELP {
echo "------------------------------------------------------------------------"
echo "$(tput bold) $pname : Automatic gain tuning$(tput sgr0)"
echo "------------------------------------------------------------------------"
echo "  Automatic gain tuning"
echo "   "
echo " $(tput bold)USAGE:$(tput sgr0)"
echo "     $0 [-h] "
echo ""
echo " $(tput bold)OPTIONS:$(tput sgr0)"
echo "     $(tput bold)-h$(tput sgr0)          help"
echo ""
echo " $(tput bold)INPUT:$(tput sgr0)"
echo ""
echo " $(tput bold)OUTPUT:$(tput sgr0)"
echo ""
echo " $(tput bold)NOTES:$(tput sgr0)"
echo ""
echo "------------------------------------------------------------------------"
}


printHELP1 ()
{
    printf "%25s       Automatic gain tuning\n" "$0" 
}




# Transform long options to short ones
singlelinehelp=0
for arg in "$@"; do
  shift
  case "$arg" in
    "--help") set -- "$@" "-h" ;;
    "--help1") 
set -- "$@" "-h" 
singlelinehelp=1;
;;
    *)        set -- "$@" "$arg"
  esac
done


while getopts :h FLAG; do
  case $FLAG in
    h)  #show help
      if [ "$singlelinehelp" -eq "0" ]; then
      printHELP
      else
      printHELP1
      fi
      exit
      ;;
    \?) #unrecognized option - show help
      echo -e \\n"Option -${BOLD}$OPTARG${NORM} not allowed."
      printHELP
      ;;
  esac
done

shift $((OPTIND-1)) 







if [ "$1" = "help" ] || [ "$#" -ne $NBARGS ]; then
if [ "$#" -ne $NBARGS ]; then
    echo "$(tput setaf 1)$(tput bold) Illegal number of parameters ($NBARGS params required, $# entered) $(tput sgr0)"
fi
printHELP
        exit
fi










loopnb=$(cat LOOPNUMBER)


./AOloopControl -n $pname << EOF
aolautotunegains $loopnb aol${loopnb}_autogain
exitCLI
EOF


