#!/bin/bash


NBARGS=1
pname=`echo "$0" | sed "s/\.\///g"`




function printHELP {
echo "------------------------------------------------------------------------"
echo "$(tput bold) $pname : Compute real-time WFS residual image $(tput sgr0)"
echo "------------------------------------------------------------------------"
echo "  Align Pyramid camera"
echo "   "
echo " $(tput bold)USAGE:$(tput sgr0)"
echo "     $0 [-h] <averaging coeff>"
echo ""
echo " $(tput bold)OPTIONS:$(tput sgr0)"
echo "     $(tput bold)-h$(tput sgr0)          help"
echo ""
echo " $(tput bold)INPUT:$(tput sgr0)"
echo "   <averaging coeff>    averaging coefficient"
echo ""
echo " $(tput bold)OUTPUT:$(tput sgr0)"
echo "creates streams :"
echo "        aol<loop>_wfsres"
echo "        aol<loop>_wfsres_ave"
echo "        aol<loop>_wfsres_rms"
echo ""
echo "------------------------------------------------------------------------"
}


printHELP1 ()
{
    printf "%25s       Compute real-time WFS residual image\n" "$0" 
}




# Transform long options to short ones
singlelinehelp=0
for arg in "$@"; do
  shift
  case "$arg" in
    "--help") set -- "$@" "-h" ;;
    "--help1") 
set -- "$@" "-h" 
singlelinehelp=1;
;;
    *)        set -- "$@" "$arg"
  esac
done


while getopts :h FLAG; do
  case $FLAG in
    h)  #show help
      if [ "$singlelinehelp" -eq "0" ]; then
      printHELP
      else
      printHELP1
      fi
      exit
      ;;
    \?) #unrecognized option - show help
      echo -e \\n"Option -${BOLD}$OPTARG${NORM} not allowed."
      printHELP
      ;;
  esac
done

shift $((OPTIND-1)) 







if [ "$1" = "help" ] || [ "$#" -ne $NBARGS ]; then
if [ "$#" -ne $NBARGS ]; then
    echo "$(tput setaf 1)$(tput bold) Illegal number of parameters ($NBARGS params required, $# entered) $(tput sgr0)"
fi
printHELP
        exit
fi









loopnb=$(cat LOOPNUMBER)

./AOloopControl -n aol${loopnb}latency << EOF
#readshmim aol${loopnb}_imWFS0
#readshmim aol${loopnb}_wfsref
#readshmim aol${loopnb}_imWFS0tot
aolmkwfsres ${loopnb} $1
exitCLI
EOF
