#!/bin/bash



# number of arguments to script
NBARGS=3


# ======================= PROCESS NAME =================================
pname=`echo "$0${loopnb}" | sed "s/\.\///g"`





function printHELP {
echo "------------------------------------------------------------------------"
echo "$(tput bold) $pname : Slow offload of WFS residuals to WFS reference $(tput sgr0)"
echo "------------------------------------------------------------------------"
echo "offloads aol#_wfsres_ave to aol#_wfszpoX"
echo "   "
echo " $(tput bold)USAGE:$(tput sgr0)"
echo "     $0 [-h] <time interval> <averaging coeff> <wfszpo channel>"
echo ""
echo " $(tput bold)OPTIONS:$(tput sgr0)"
echo "     $(tput bold)-h$(tput sgr0)          help"
echo ""
echo " $(tput bold)INPUT:$(tput sgr0)"
echo "     <time interval>       time between updates [sec]"
echo "     <averaging coeff>     averaging coefficient"
echo "     <wfszpo channel>      zero point offset channel"
echo ""
echo "------------------------------------------------------------------------"
}


printHELP1 ()
{
    printf "%25s       Compute real-time WFS residual image\n" "$0" 
}




# Transform long options to short ones
singlelinehelp=0
for arg in "$@"; do
  shift
  case "$arg" in
    "--help") set -- "$@" "-h" ;;
    "--help1") 
set -- "$@" "-h" 
singlelinehelp=1;
;;
    *)        set -- "$@" "$arg"
  esac
done





while getopts :h FLAG; do
  case $FLAG in
    h)  #show help
      if [ "$singlelinehelp" -eq "0" ]; then
      printHELP
      else
      printHELP1
      fi
      exit
      ;;
    \?) #unrecognized option - show help
      echo -e \\n"Option -${BOLD}$OPTARG${NORM} not allowed."
      printHELP
      ;;
  esac
done

shift $((OPTIND-1)) 






if [ "$1" = "help" ] || [ "$#" -ne $NBARGS ]; then
if [ "$#" -ne $NBARGS ]; then
    echo "$(tput setaf 1)$(tput bold) Illegal number of parameters ($NBARGS params required, $# entered) $(tput sgr0)"
fi
printHELP
        exit
fi



loopnb=$(cat LOOPNUMBER)





cnt=0

while true
do

echo "$cnt   WFS residual offset to WFS ref"
./AOloopControl -n $pname << EOF > /dev/null
readshmim aol${loopnb}_wfsres_ave
readshmim aol${loopnb}_wfsref
readshmim aol${loopnb}_wfszpo$3
im=aol${loopnb}_wfszpo$3+$2*aol${loopnb}_wfsres_ave
cpsh im aol${loopnb}_wfszpo$3	
exitCLI
EOF
let cnt=cnt+1
sleep $1

done

