#!/bin/bash



# number of arguments to script
NBARGS=0


# ======================= PROCESS NAME =================================
loopnb=$(cat LOOPNUMBER)
pname="aol${loopnb}zpwfsl"

NBWFSZPCHAN=8

function printHELP {
echo "------------------------------------------------------------------------"
echo "$(tput bold) $pname : WFS zero point offset loop$(tput sgr0)"
echo "------------------------------------------------------------------------"
echo " Create zero point WFS channels ($NBWFSZPCHAN channels)"
echo " Watch semaphore 1 on output (IDwfsref_name) -> sum all channels to update WFS zero point"
echo " Runs in separate process from RT computation"
echo "   "
echo " $(tput bold)USAGE:$(tput sgr0)"
echo "     $0 [-h] "
echo ""
echo " $(tput bold)OPTIONS:$(tput sgr0)"
echo "     $(tput bold)-h$(tput sgr0)          help"
echo ""
echo " $(tput bold)OUTPUT:$(tput sgr0)"
echo "     out.txt     output file"
echo ""
echo "------------------------------------------------------------------------"
}


# ================= OPTIONS =============================

#Parse command line flags
#If an option should be followed by an argument, it should be followed by a ":".
#Notice there is no ":" after "h". The leading ":" suppresses error messages from
#getopts. This is required to get unrecognized option code to work.

while getopts :h FLAG; do
  case $FLAG in
    h)  #show help
      printHELP
      exit
      ;;
    \?) #unrecognized option - show help
      echo -e \\n"Option -${BOLD}$OPTARG${NORM} not allowed."
      printHELP
      #If you just want to display a simple error message instead of the full
      #help, remove the 2 lines above and uncomment the 2 lines below.
      #echo -e "Use ${BOLD}$SCRIPT -h${NORM} to see the help documentation."\\n
      #exit 2
      ;;
  esac
done

shift $((OPTIND-1))  #This tells getopts to move on to the next argument.

### End getopts code ###




if [ "$1" = "help" ] || [ "$#" -ne $NBARGS ]; then
if [ "$#" -ne $NBARGS ]; then
    echo "$(tput setaf 1)$(tput bold) Illegal number of parameters ($NBARGS params required, $# entered) $(tput sgr0)"
fi
printHELP
        exit
fi




Cfits -n $pname << EOF
readshmim aol${loopnb}_wfsref
readshmim aol${loopnb}_wfsref0
aolzpwfscloop aol${loopnb}_wfszp $NBWFSZPCHAN aol${loopnb}_wfsref0 aol${loopnb}_wfsref
exit
EOF

