#!/bin/bash

# args: <confindex> <beta coeff> <max nb modes removed>
EXPECTED_ARGS=3

if [ $# -ne $EXPECTED_ARGS ]
then
  echo
  echo "-------- create control matrixes ------------"
  echo "Usage:  $0 <beta coeff> <max nb modes removed> <modestep>"
  echo "   INPUT:  <beta coeff>           : Beta coefficient (typically 0.5 to 4.0), enhances low order aberrations for SVD"
  echo "   INPUT:  <max number modes removed> : will generate matrixes with 0, 10, 20, .... number of modes removed until max number reached"
  echo "   INPUT   <modestep>            : incremental step for number of modes removed"
  echo " EXAMPLE: $0 4.0 20 5"
  echo
  exit
fi


cp ./conf/modesfreqcpa.fits .
cp ./conf/fmodes.fits .
cp ./conf/respm.fits .

loopnb=$(cat LOOPNUMBER)
confnb=$(cat conf/conf_CONFNUMBER.txt)

pname0=$0
pname=${pname0#"./"}-$loopnb


Cfits -n pname << EOF
aolnb $loopnb
loadfits "./conf/respm.fits" respm
loadfits "./conf/fmodes.fits" modesM
aolcmmake $2 respm cmat $1 $3
savefits evecM "!evecM.fits"
exit
EOF
mkdir -p ./conf${confnb}/cmat/
mv cmat_*_*.fits ./conf${confnb}/cmat/
mv evecM.fits ./conf${confnb}/
mv eigenv.dat ./conf${confnb}/
mv eigenmodesM*.fits ./conf${confnb}/
mv eigenmodesrespM*.fits ./conf${confnb}/
