#! /bin/bash

EXPECTED_ARGS=2

if [ $# -ne $EXPECTED_ARGS ]
then
  echo
  echo "------ Copy FITS files to shared memory -----"
  echo
  echo "  $0 <FITS file> <shared memory stream name>"
  echo
  exit
fi

pname0=$0
pname=${pname0#"./"}-$loopnb



Cfits -n pname << EOF
loadfits "$1" im
cpsh im "$2"
exit
EOF


