#! /bin/bash

EXPECTED_ARGS=2

if [ $# -ne $EXPECTED_ARGS ]
then
  echo
  echo "------ cross-product of two data cubes ------"
  echo 
  echo " Usage: $0 <FITS file> <FITS file>"
  echo "    output: xp.fits"
  echo
exit
fi

Cfits << EOF
loadfits "$1" im1
loadfits "$2" im2
aolcrossp im1 im2 xp
savefits xp "!xp.fits"
exit
EOF
