#! /bin/bash

EXPECTED_ARGS=4

if [ $# -ne $EXPECTED_ARGS ]
then
  echo
  echo "------ Acquires Response Matrix ------"
  echo 
  echo "Usage: acquRespM <amplitude [nm]> <output: respm filename> <output: ref filename> <output: RM amplitude text file>"
  echo 
  exit
fi

mkdir -p ./tmp/

# number of images per DM state
NBave=100

# modulation amplitude [um DM displacement]
ampl=$(echo " $1 * 0.001" | bc -l)

# number of loop per matrix generation
NBloops=1

# frame delay offset [number of frames]
fdelay=4

# number of matrixes generated (will be continuously averaged)
NBmat=10000




# creates files "respm.fits" and "refwfs.fits"

loopnb=$(cat LOOPNUMBER)


Cfits -n aolacqresp-$loopnb << EOF
aolnb $loopnb
readshmim aol${loopnb}_wfsdark
aolacqresp $NBave $ampl $NBloops $fdelay $NBmat
exit
EOF

cp ./tmp/respm.fits $2
cp ./tmp/refwfs.fits $3
cp ./tmp/RM_optsign.txt $4

