#! /bin/bash

EXPECTED_ARGS=0

if [ $# -ne $EXPECTED_ARGS ]
then
  echo
  echo "------ Align Pyramid camera -------"
  echo
  echo "   no argument"
  echo
  exit
fi

loopnb=$(cat LOOPNUMBER)
confnb=$(cat ./conf/conf_CONFNUMBER.txt)


pname0=$0
pname=${pname0#"./"}-$loopnb


Cfits -n pname << EOF
readshmim aol${loopnb}_wfs
readshmim aol${loopnb}_wfsdark
cp aol${loopnb}_wfsdark wfsdark
loadfits "./conf/refwfs0.fits" imref
scexaopywfscamalign aol${loopnb}_wfs
imdiff=imwfs-imref
savefits imdiff "!./tmp/imdiff.fits"
exit
EOF
