#!/bin/bash


# ====================== USER EDITS THIS SECTION =======================

execname="AOloopControl"

# default parameters

LOOPNAME="pyramid" # name of the control loop
LOOPNUMBER_default=2  # loop number

dmC="dmdisp3" # DM control channel
dmRM="dmdisp7" # DM actuation channel for RM matrix
wfsimcam="imcam" # WFS camera image

shmimviewexec="shmimview"
shmimmonexec="shmimmon"


# ======================== END OF USER EDIT SECTION =====================





# ===================== TEST MODE ========================
testdmsize=20






# =================== some initial setup =======================

LINES=$( tput lines )
COLUMNS=$( tput cols )
let " nbwlines = $LINES - 10 "
let " nbwcols = $COLUMNS - 10 "



LOOPNUMBER_file="LOOPNUMBER"
confnbfile="./conf/conf_CONFNUMBER.txt"

mkdir -p conf
mkdir -p status
mkdir -p tmp
mkdir -p conf/zRM


# LOOPNUMBER (loop number)
if [ ! -f $LOOPNUMBER_file ]
then
	echo "creating loop number"
	echo "$LOOPNUMBER_default" > $LOOPNUMBER_file
else
	LOOPNUMBER=$(cat $LOOPNUMBER_file)
	echo "LOOPNUMBER = $LOOPNUMBER"
fi


outmesg="/tmp/aol${LOOPNUMBER}confout"
rm $outmesg
touch $outmesg


# CONFSELECTED (conf numnber)
if [ ! -f $confnbfile ]
then
	echo "creating configuration number"
	echo "$CONFSELECTED_default" > ./conf/conf_CONFNUMBER.txt
else
	CONFSELECTED=$(cat $confnbfile)
	echo "selected configuration = $CONFSELECTED"
fi



# connect to WFS camera
echo "connecting to camera"
ln -sf /tmp/${wfsimcam}.im.shm /tmp/aol${LOOPNUMBER}_wfsim.im.shm




# loop name
echo "$LOOPNAME" > ./conf/conf_LOOPNAME.txt
echo "loop name : $LOOPNAME"




tempfile=`tempfile 2>/dev/null` || tempfile=/tmp/test$$
trap "rm -f $tempfile" 0 1 2 5 15










# ================ FREQUENTLY USED FUNCTIONS ===================

echo "FUNCTIONS..."






function Fits2shm {
$execname << EOF # move file to shared memory
loadfits "$1" im
imcp2shm im $2
quit
EOF
}




# SetDark <confnb> <camgain>
function SetDark {
file="./conf$1/conf_pyrloopfrequ.txt"
ok=1

if [ -f $file ]
	then
	pyfreq=$(echo "$(cat $file)")
	else
	echo "CANNOT READ FILE ${file}"
	ok=0
fi

file="$PWD/darks/dark_${pyfreq}_$2.fits"
if [ ! -f $file ]
	then
	echo "CANNOT READ FILE ${file}"
	ok=0
fi

if [ ${ok} -eq 1 ]
then
ln -snf ${file} "$PWD/conf/dark.fits" &> ${outmesg}
Fits2shm "./conf/dark.fits" aol${LOOPNUMBER}_wfsdark &> ${outmesg}
fi

}


# SetDMmodes <confnb>
function SetDMmodes {
file="./conf$1/fmodes.fits"
ok=1
if [ -f $file ]
then
ln -snf $PWD/conf$1/fmodes.fits $PWD/conf/fmodes.fits
ln -snf $PWD/conf$1/modesfreqcpa.fits $PWD/conf/modesfreqcpa.fits
Fits2shm "./conf/fmodes.fits" "aol${LOOPNUMBER}_DMmodes"
else
echo "CANNOT READ FILE ${file}"
fi
}








function ReaddmCname {
file="./conf/conf_dmC_name.txt"
if [ -a $file ]
	then
	dmC=$(echo "$(cat $file)")
	else
	dmC="dmC" #default
fi
# DM correction channel
echo "linking to dm correction channel"
rm /tmp/aol${LOOPNUMBER}_dmC.im.shm 
ln -s /tmp/${dmC}.im.shm /tmp/aol${LOOPNUMBER}_dmC.im.shm
}


function ReaddmRMname {
file="./conf/conf_dmRM_name.txt"
if [ -a $file ]
	then
	dmRM=$(echo "$(cat $file)")
	else
	dmRM="dmRM" #default
fi
# DM response matrix channel
echo "linking to dm resp mat channel"
rm /tmp/aol${LOOPNUMBER}_dmRM.im.shm 
ln -s /tmp/${dmRM}.im.shm /tmp/aol${LOOPNUMBER}_dmRM.im.shm
}


function Readwfsimcamname {
file="./conf/conf_wfsim_name.txt"
if [ -a $file ]
	then
	wfsimcam=$(echo "$(cat $file)")
	else
	wfsimcam="wfsimcam" #default
fi
# WFS raw image
echo "linking to WFS camera"
ln -sf /tmp/${wfsimcam}.im.shm /tmp/aol${LOOPNUMBER}_wfsim.im.shm
}


function ReadLoopDelay {
file="./conf/conf_loopdelayms.txt"
if [ -a $file ]
	then
	loopdelayms=$(echo "$(cat $file)")
	else
	loopdelayms=10.0 #default
fi
}




function ReadWFSdarkfname {
file="./conf/conf_wfsdark_fname.txt"
if [ -a $file ]
	then
	wfsdarkfname=$(echo "$(cat $file)")
	else
	wfsdarkfname="wfsdark.fits" #default
fi
rm /tmp/aol${LOOPNUMBER}_wfsdark.im.shm
Fits2shm ${wfsdarkfname} aol${LOOPNUMBER}_wfsdark
}


function ReadWFSmaskfname {
file="./conf/conf_wfsmask_fname.txt"
if [ -a $file ]
	then
	wfsmaskfname=$(echo "$(cat $file)")
	else
	wfsmaskfname="wfsmask.fits" #default
fi
rm /tmp/aol${LOOPNUMBER}_wfsmask.im.shm
Fits2shm ${wfsmaskfname} aol${LOOPNUMBER}_wfsmask
}



function ReadDMmaskfname {
file="./conf/conf_dmmask_fname.txt"
if [ -a $file ]
	then
	dmmaskfname=$(echo "$(cat $file)")
	else
	dmmaskfname="dmmask.fits" #default
fi
rm /tmp/aol${LOOPNUMBER}_dmmask.im.shm
Fits2shm ${dmmaskfname} aol${LOOPNUMBER}_dmmask
}





#  System response and control

function ReadCPAmax {
file="./conf/conf_cpamax.txt"
if [ -a $file ]
	then
	cpamax=$(echo "$(cat $file)")
	else
	cpamax="10.0" #default
fi
}

function ReadDMmodesname {
file=$( cat ./conf/conf_DMmodes_name.txt )
rm /tmp/aol${LOOPNUMBER}_DMmodes.im.shm
$execname << EOF
loadfits "$file" dmmodes
cpsh dmmodes aol${LOOPNUMBER}_DMmodes
exit
EOF
cp $PWD/${file} $PWD/conf/fmodes.fits
}


function ReadrespMname {
file="./conf/conf_respM_name.txt"
if [ -a $file ]
	then
	respM=$(echo "$(cat $file)")
	else
	respM="respM" #default
fi
ln -sf /tmp/${respM}.im.shm /tmp/aol${LOOPNUMBER}_respM.im.shm
}


function ReadWFSrefname {
file="./conf/conf_wfsref_name.txt"
if [ -a $file ]
	then
	wfsref=$(echo "$(cat $file)")
	else
	wfsref="WFSref" #default
fi
ln -sf /tmp/${respM}.im.shm /tmp/aol${LOOPNUMBER}_wfsref.im.shm
}









function ReadLoopGain {
file="./conf/conf_loopgain.txt"
if [ -a $file ]
	then
	loopgain=$(echo "$(cat $file)")
	else
	loopgain="0.000" #default
fi
}


function ReadLoopMaxLim {
file="./conf/conf_loopmaxlim.txt"
if [ -a $file ]
	then
	loopmaxlim=$(echo "$(cat $file)")
	else
	loopmaxlim="0.100"
fi
}


function ReadLoopMultCoeff {
file="./conf/conf_loopmultcoeff.txt"
if [ -a $file ]
	then
	loopmultcoeff=$(echo "$(cat $file)")
	else
	loopmultcoeff="0.999"
fi
}



function ReadDMturbampl {
file="./conf/conf_dmturbampl.txt"
if [ -a $file ]
	then
	dmturbampl=$(echo "$(cat $file)")
	else
	dmturbampl=0.1 #default
fi
tmux new-session -d -s DMturbamp
tmux send-keys -t DMturbamp "$execname " C-m
tmux send-keys -t DMturbamp "aoloopcontroldmturampl $dmturbampl" C-m
tmux send-keys -t DMturbamp "exit" C-m
tmux send-keys -t DMturbamp "exit" C-m
}


function ReadDMturbtint {
file="./conf/conf_dmturbtint.txt"
if [ -a $file ]
	then
	dmturbtint=$(echo "$(cat $file)")
	else
	dmturbtint=0.1 #default
fi
tmux new-session -d -s DMturbtint
tmux send-keys -t DMturbtint "$execname " C-m
tmux send-keys -t DMturbtint "aoloopcontroldmturtint ${dmturbtint}" C-m
tmux send-keys -t DMturbtint "exit" C-m
tmux send-keys -t DMturbtint "exit" C-m
}




function ReadTestDMsize {
file="./conf/conf_testdmsize.txt"
if [ -a $file ]
	then
	testdmsize=$(echo "$(cat $file)")
	else
	testdmsize=20 #default
fi
# start DM channels
tmux kill-session -t aosim${LOOPNUMBER}dmcomb
tmux new-session -d -s aosim${LOOPNUMBER}dmcomb 
tmux send-keys -t aosim${LOOPNUMBER}dmcomb "$execname" C-m
tmux send-keys -t aosim${LOOPNUMBER}dmcomb "aolcontroldmsetsize ${testdmsize}" C-m
tmux send-keys -t aosim${LOOPNUMBER}dmcomb "aolcontroldmsetname aosimdmctrl" C-m
tmux send-keys -t aosim${LOOPNUMBER}dmcomb "aolcontrolDMcomb" C-m
}


function CheckLoopConfiguration {
confOK=1
echo "" > confOK_errmsg.txt

file="./conf/conf_loopgain.txt"
if [ ! -f $file ]; then
	echo "FILE $file is missing" >> confOK_errmsg.txt
	confOK=0
	fi

file="./conf/conf_loopmaxlim.txt"
if [ ! -f $file ]; then
	echo "FILE $file is missing" >> confOK_errmsg.txt
	confOK=0
	fi
	
file="./conf/conf_loopmultcoeff.txt"
if [ ! -f $file ]; then
	echo "FILE $file is missing" >> confOK_errmsg.txt
	confOK=0
	fi

clear
if [ $confOK -eq 0 ]; then
	echo "CONFIGURATION IS NOT COMPLETE"
	cat confOK_errmsg.txt
else
	echo "CONFIGURATION IS COMPLETE"
fi
sleep 2
}












function TestModeStart {

# start DM channels
tmux kill-session -t aosim${LOOPNUMBER}dmcomb
tmux new-session -d -s aosim${LOOPNUMBER}dmcomb 
tmux send-keys -t aosim${LOOPNUMBER}dmcomb "$execname" C-m
tmux send-keys -t aosim${LOOPNUMBER}dmcomb "aolcontroldmsetsize ${testdmsize}" C-m
tmux send-keys -t aosim${LOOPNUMBER}dmcomb "aolcontroldmsetname aosimdmctrl" C-m
tmux send-keys -t aosim${LOOPNUMBER}dmcomb "aolcontrolDMcomb" C-m

mkdir -p testconf
echo "$execname -n aol${LOOPNUMBER}test << EOF" > script_aol${LOOPNUMBER}test 
echo "AOsystsim" >> script_aol${LOOPNUMBER}test 
chmod +x script_aol${LOOPNUMBER}test 

tmux new-session -d -s aol${LOOPNUMBER}test
echo "ON" > ./status/testloopstatus.txt
tmux send-keys -t aol${LOOPNUMBER}test "./script_aol${LOOPNUMBER}test" C-m

echo "aosimdmctrl2" > ./conf/conf_dmC_name.txt
ReaddmCname
echo "aosimdmctrl3" > ./conf/conf_dmRM_name.txt
ReaddmRMname
echo "aosimwfsim" > ./conf/conf_wfsim_name.txt
Readwfsimcamname

echo "0.1" > ./conf/conf_loopgain.txt
ReadLoopGain

echo "1.0" > ./conf/conf_loopmaxlim.txt
ReadLoopMaxLim 

echo "0.99" > ./conf/conf_loopmultcoeff.txt
ReadLoopMultCoeff
}

function TestModeStop {
pkill aol${LOOPNUMBER}test
echo "OFF" > ./status/testloopstatus.txt
}


function TestStartTurb {
mkdir -p ./conf/turb
tmux kill-session -t aosim${LOOPNUMBER}dmturb
tmux new-session -d -s aosim${LOOPNUMBER}dmturb 
tmux send-keys -t aosim${LOOPNUMBER}dmturb "$execname" C-m
tmux send-keys -t aosim${LOOPNUMBER}dmturb "aolcontroldmsetsize ${testdmsize}" C-m
tmux send-keys -t aosim${LOOPNUMBER}dmturb "aolcontroldmsetname aosimdmctrl" C-m
tmux send-keys -t aosim${LOOPNUMBER}dmturb "aoloopcontrolDMturb" C-m

tmux kill-session -t aosim${LOOPNUMBER}dmturbctrl
tmux new-session -d -s aosim${LOOPNUMBER}dmturbctrl
tmux send-keys -t aosim${LOOPNUMBER}dmturbctrl "$execname" C-m
tmux send-keys -t aosim${LOOPNUMBER}dmturbctrl "aoloopcontroldmturampl 0.1" C-m
tmux send-keys -t aosim${LOOPNUMBER}dmturbctrl "aoloopcontroldmturtint 10000" C-m
tmux send-keys -t aosim${LOOPNUMBER}dmturbctrl "aoloopcontroldmturws 1.0" C-m
tmux send-keys -t aosim${LOOPNUMBER}dmturbctrl "aoloopcontroldmturlo 0.0" C-m

}

function TestStopTurb {
tmux kill-session -t aosim${LOOPNUMBER}dmturb
}




# =================== READ CONFIGURATION====================================

# hardware I/O [shared memory]
ReaddmCname
ReaddmRMname
Readwfsimcamname
ReadLoopDelay


# I/O pre-processing [FITS files]
ReadWFSdarkfname
ReadWFSmaskfname
ReadDMmaskfname
ReadWFSreffname

# System response and control
ReadCPAmax
ReadDMmodesname
ReadrespMname

ReadLoopGain
ReadLoopMaxLim
ReadLoopMultCoeff









# =================== STATE MACHINE ====================================
state="menutop"


confnb=0
confselected=1

menuconfmanage_default=0








echo "START STATE MACHINE"

while true; do

stateok=0



# =====================================================
# ===================== TOP MENU ======================
# =====================================================

if [ $state = "menutop" ]; then
stateok=1
confselected=$(cat "./conf/conf_CONFNUMBER.txt")
menuname="TOP MENU \n [Active conf = ${confselected}]"


menuitems=( "C" "Configure/link AO loop" )
menuitems+=( "L" "Control AO loop" )
menuitems+=( "T" "Test mode: simulated AO system" )
menuitems+=( "V" "View / monitor" )



dialog --title "AO loop top menu" \
--ok-label "Select" \
--cancel-label "Exit" \
--default-item "${menutop_default}" \
 --menu "$menuname" \
 50 80 100 "${menuitems[@]}"  2> $tempfile

retval=$?
choiceval=$(cat $tempfile)

case $retval in
   0) # button
	case $choiceval in
   	 C) 
menutop_default="C"
state="menuconfigureloop"
;;   
   	 L) 
menutop_default="L"
state="menucontrolloop"
;;
   	 T) 
menutop_default="T"
state="menutestmode"   
;;
   	 V) 
menutop_default="V"
state="menuview"   
;;
	esac;;
   1) state="menuexit";;   
   255) state="menuexit";;
esac
fi

















# =====================================================
# =============== CONFIGURE AO LOOP ===================
# =====================================================

if [ $state = "menuconfigureloop" ]; then
stateok=1
menuname="\Zb\Zu REVIEW LOOP CONFIGURATION\Zn\n
Loop configuration is stored in ./conf/ directory\n
Files specified in this configuration menu get linked/loaded to shared memory:\n
HARDWARE I/O:\n
     /tmp/aol${LOOPNUMBER}_dmC.im.shm           DM correction channel\n
     /tmp/aol${LOOPNUMBER}_dmRM.im.shm          DM resp matrix channel\n
     /tmp/aol${LOOPNUMBER}_wfsim.im.shm         WFS camera image\n
I/O PRE-PROCESSING:\n
     /tmp/aol${LOOPNUMBER}_wfsdark.im.shm       WFS dark\n
SYSTEM ZONAL RESPONSE AND CONTROL:\n
     /tmp/aol${LOOPNUMBER}_wfsmask.im.shm       WFS mask\n
     /tmp/aol${LOOPNUMBER}_dmmask.im.shm        DM mask\n
     /tmp/aol${LOOPNUMBER}_wfsref.im.shm        WFS ref\n
SYSTEM MODAL RESPONSE AND CONTROL:\n
     /tmp/aol${LOOPNUMBER}_DMmodes.im.shm       DM modes\n
     /tmp/aol${LOOPNUMBER}_RM.im.shm            Response Matrix\n
     /tmp/aol${LOOPNUMBER}_CM.im.shm            Control Matrix\n
          "

confOK=1



menuitems=( "1 ->" "\Zb\Zr        HARDWARE I/O LINKS [shared memory]           \Zn" )

dmCfile="/tmp/${dmC}.im.shm"
if [ -f $dmCfile ]; then
dmCOKstr="\Z2    OK    \Zn"
else
dmCOKstr="\Z1\Zb  MISSING \Zn"
confOK=0
fi
menuitems+=( "dmC" "[${dmCOKstr}] DM control channel    {\Z4${dmC}\Zn}" )


dmRMfile="/tmp/${dmRM}.im.shm"
if [ -f $dmRMfile ]; then
dmRMOKstr="\Z2    OK    \Zn"
else
dmRMOKstr="\Z1\Zb  MISSING \Zn"
confOK=0
fi
menuitems+=( "dmRM" "[${dmRMOKstr}] DM RM acqu channel    {\Z4${dmRM}\Zn}" )


wfsimcamfile="/tmp/${wfsimcam}.im.shm"
if [ -f $wfsimcamfile ]; then
wfsimcamOKstr="\Z2    OK    \Zn"
else
wfsimcamOKstr="\Z1\Zb  MISSING \Zn"
confOK=0
fi
menuitems+=( "wfs" "[${wfsimcamOKstr}] WFS camera image      {\Z4${wfsimcam}\Zn}" )


menuitems+=( "delay" "             LOOP delay            ${loopdelayms} ms" )





menuitems+=( "-" " " )
menuitems+=( "2 ->" "\Zb\Zr             I/O PRE-PROCESSING [FITS files]         \Zn" )
 

wfsdarkfname=$( cat ./conf/conf_wfsdark_fname.txt )
if [ -f "$wfsdarkfname" ] && [ -f "./conf/conf_wfsdark_fname.txt" ]; then
wfsdarkfnameOKstr="\Z2    OK    \Zn"
else
wfsdarkfnameOKstr="\Z5 OPTIONAL \Zn"
confOK=0
fi
menuitems+=( "dark" "[${wfsdarkfnameOKstr}] WFS dark              {\Z4${wfsdarkfname}\Zn}" )



acqudarkstat=$( cat ./status/stat_acqudark.txt )
if [[ -f "./status/stat_acqudark.txt" && ( "$acqudarkstat" = " ON" || "$acqudarkstat" = "OFF" ) ]]; then
echo "OK"
else
echo "OFF" > ./status/stat_acqudark.txt
fi

acqudarkstat=$( cat ./status/stat_acqudark.txt )
if [ "${acqudarkstat}" = "OFF" ];
then
menuitems+=( "adark_on" "             START acquire WFS dark acquisition" )
fi
if [ "${acqudarkstat}" = " ON" ];
then
menuitems+=( "adarkoff" "\Z1\Zr             STOP WFS dark acquisition             \Zn" )
fi





menuitems+=( "-" " " )
menuitems+=( "3 ->" "\Zb\Zr       SYSTEM CALIBRATION (ZONAL)                    \Zn" )

rmamplum=0.05
if [ -f "./conf/conf_RMamplum.txt" ]; then
rmamplum=$( cat ./conf/conf_RMamplum.txt )
fi
menuitems+=( "rmamp" "            RM amplitude           ${rmamplum} um" )

rmdelays=0.05
if [ -f "./conf/conf_RMdelays.txt" ]; then
rmdelays=$( cat ./conf/conf_RMdelays.txt )
fi
menuitems+=( "rmdelay" "            RM time delay          ${rmdelays} sec" )

rmfrave=5
if [ -f "./conf/conf_RMfrave.txt" ]; then
rmfrave=$( cat ./conf/conf_RMfrave.txt )
fi
menuitems+=( "rmnbfr" "            RM frame averaging     ${rmfrave} frames" )



zrespfname=$( cat ./conf/conf_zrespmatfname.txt )
if [ -f "$zrespfname" ] && [ -f "./conf/conf_zrespmatfname.txt" ]; then
zrespfnameOKstr="\Z2    OK    \Zn"
else
zrespfnameOKstr="\Z5 OPTIONAL \Zn"
confOK=0
fi
menuitems+=( "zmatn" "[${zrespfnameOKstr}] Zonal RM name         {\Z4${zrespfname}\Zn}" ) 


zrespstat=$( cat ./status/stat_zresp.txt )
if [[ -f "./status/stat_zresp.txt" && ( "$zrespstat" = " ON" || "$zrespstat" = "OFF" ) ]]; then
echo "OK"
else
echo "OFF" > ./status/stat_zresp.txt
fi


if [ "${zrespstat}" = "OFF" ];
then
menuitems+=( "zresp_on" "             START zonal RM acquisition" )
fi

if [ "${zrespstat}" = " ON" ];
then
menuitems+=( "zrespoff" "\Z1\Zr             STOP zonal RM acquisition             \Zn" )
fi




  
wfsmaskfname=$( cat ./conf/conf_wfsmask_fname.txt )
if [ -f "$wfsmaskfname" ] && [ -f "./conf/conf_WFSmask_fname.txt" ]; then
wfsmaskfnameOKstr="\Z2    OK    \Zn"
else
wfsmaskfnameOKstr="\Z5 OPTIONAL \Zn"
confOK=0
fi
menuitems+=( "wfsM" "[${wfsmaskfnameOKstr}] WFS pixel mask        {\Z4${wfsmaskfname}\Zn}" )


dmmaskfname=$( cat ./conf/conf_dmmask_fname.txt )
if [ -f "$dmmaskfname" ] && [ -f "./conf/conf_dmmask_fname.txt" ]; then
dmmaskfnameOKstr="\Z2    OK    \Zn"
else
dmmaskfnameOKstr="\Z5 OPTIONAL \Zn"
confOK=0
fi
menuitems+=( "dmM" "[${dmmaskfnameOKstr}] DM pixel mask         {\Z4${dmmaskfname}\Zn}" )




wfsreffname=$( cat ./conf/conf_wfsref_fname.txt )
if [ -f $wfsreffname ] && [ -f "./conf/conf_wfsref_fname.txt" ]; then
wfsreffnameOKstr="\Z2    OK    \Zn"
else
wfsreffnameOKstr="\Z1\Zb  MISSING \Zn"
confOK=0
fi
menuitems+=( "wfsref" "[${wfsreffnameOKstr}] WFS reference         {\Z4${wfsreffname}\Zn}" )


acquwfsrefstat=$( cat ./status/stat_acquwfsref.txt )
if [[ -f "./status/stat_acquwfsref.txt" && ( "$acquwfsrefstat" = " ON" || "$acquwfsrefstat" = "OFF" ) ]]; then
echo "OK"
else
echo "OFF" > ./status/stat_acquwfsref.txt
fi

acquwfsrefstat=$( cat ./status/stat_acquwfsref.txt )
if [ "${acquwfsrefstat}" = "OFF" ];
then
menuitems+=( "awfsref_on" "             START new WFS ref acquisition" )
fi
if [ "${acquwfsrefstat}" = " ON" ];
then
menuitems+=( "awfsrefoff" "\Z1\Zr             STOP WFS ref acquisition              \Zn" )
fi













menuitems+=( "-" " " )
menuitems+=( "4 ->" "\Zb\Zr     SYSTEM MODAL RESPONSE AND CONTROL               \Zn" )


menuitems+=( "mkModes" "   Make new DM control modes file" )

DMmodes=$( cat ./conf/conf_DMmodes_name.txt )
if [ -f "$DMmodes" ] && [ -f "./conf/conf_DMmodes_name.txt" ]; then
DMmodesOKstr="\Z2    OK    \Zn"
else
DMmodesOKstr="\Z1\Zb  MISSING \Zn"
confOK=0
fi
menuitems+=( "DMmodes" "[${DMmodesOKstr}] DM control modes     {\Z4${DMmodes}\Zn}" )


respMfile="/tmp/${respM}.im.shm"
if [ -f $respMfile ]; then
respMOKstr="\Z2    OK    \Zn"
else
respMOKstr="\Z1\Zb  MISSING \Zn"
confOK=0
fi
menuitems+=( "RM" "[${respMOKstr}] Response Matrix      {\Z4${respM}\Zn}" )







menuitems+=( "-" " " )


menuitems+=( "c" "check configuration" )

state="menutop"


dialog --colors --title "LOOP CONFIGURATION" \
--ok-label "Select" \
--cancel-label "Top" \
--help-button --help-label "Exit" \
--default-item "${menucontrolloop_default}" \
 --menu "$menuname" \
 $nbwlines $nbwcols 100 "${menuitems[@]}"  2> $tempfile


retval=$?
choiceval=$(cat $tempfile)


case $retval in
   0) # button
	case $choiceval in
	-)
state="menuconfigureloop"
;;
	dmC)
exec 3>&1;
dmC=$(dialog --inputbox "dmC" 0 0 "$dmC" 2>&1 1>&3);
#exitcode=$?;
exec 3>&-;
#echo $result $exitcode;
echo "$dmC" > ./conf/conf_dmC_name.txt
ReaddmCname
menucontrolloop_default="dmC"
state="menuconfigureloop"
;;
	dmRM)
exec 3>&1;
dmRM=$(dialog --inputbox "dmRM" 0 0 "$dmRM" 2>&1 1>&3);
exec 3>&-;
echo "$dmRM" > ./conf/conf_dmRM_name.txt
ReaddmRMname
menucontrolloop_default="dmRM"
state="menuconfigureloop"
;;
	wfs)
exec 3>&1;
wfsimcam=$(dialog --inputbox "WFS image" 0 0 "$wfsimcam" 2>&1 1>&3);
exec 3>&-;
echo "$wfsimcam" > ./conf/conf_wfsim_name.txt
Readwfsimcamname
menucontrolloop_default="wfs"
state="menuconfigureloop"
;;

	delay)
exec 3>&1;
loopdelayms=$(dialog --inputbox "Loop Delay [ms]" 0 0 "$loopdelayms" 2>&1 1>&3);
exec 3>&-;
echo "$loopdelayms" > ./conf/conf_loopdelayms.txt
ReadLoopDelay
menucontrolloop_default="delay"
state="menuconfigureloop"
;;



	dark)
exec 3>&1;
wfsdarkfname=$(dialog --title "Select WFS dark" --stdout --fselect "${wfsdarkfname}" $nbwlines $nbwcols)
echo "$wfsdarkfname" > ./conf/conf_wfsdark_fname.txt
ReadWFSdarkfname
menucontrolloop_default="dark"
state="menuconfigureloop"
;;
	adark_on)
acqdarkstat=" ON"
echo " ON" > ./status/stat_acqudark.txt
tmux new-session -d -s adark
#tmux send-keys -t adark "./aol" C-m
menucontrolloop_default="adarkoff"
state="menuconfigureloop"
;;
	adarkoff)
acqdarkstat="OFF"
echo "OFF" > ./status/stat_acqudark.txt
tmux kill-session -t adark
menucontrolloop_default="adark_on"
state="menuconfigureloop"
;;






	rmamp)
exec 3>&1;
rmamplum=$(dialog --inputbox "RM amplitude [um]" 0 0 "$rmamplum" 2>&1 1>&3);
exec 3>&-;
echo "$rmamplum" > ./conf/conf_RMamplum.txt
menucontrolloop_default="rmamp"
state="menuconfigureloop"
;;
	rmdelay)
exec 3>&1;
rmdelays=$(dialog --inputbox "RM time delay [s]" 0 0 "$rmdelays" 2>&1 1>&3);
exec 3>&-;
echo "$rmdelays" > ./conf/conf_RMdelays.txt
menucontrolloop_default="rmdelay"
state="menuconfigureloop"
;;
	rmnbfr)
exec 3>&1;
rmfrave=$(dialog --inputbox "RM frame averaging" 0 0 "$rmfrave" 2>&1 1>&3);
exec 3>&-;
echo "$rmfrave" > ./conf/conf_RMfrave.txt
menucontrolloop_default="rmnbfr"
state="menuconfigureloop"
;;



	zmatn)
zrespmfname=$(dialog --title "Select Zonal RM" --stdout --title "Select zonal RM" --fselect "$zrespmfname" $nbwlines $nbwcols)
#exec 3>&1;
#zrespmatfanme=$(dialog --inputbox "zonal response matrix name" 0 0 "$zrespmatfname" 2>&1 1>&3);
#exec 3>&-;
echo "$zrespmfname" > ./conf/conf_zrespmatfname.txt
menucontrolloop_default="zmatn"
state="menuconfigureloop"
;;
	zresp_on)
zrespstat=" ON"
echo " ON" > ./status/stat_zresp.txt
tmux new-session -d -s zresp
tmux send-keys -t zresp "./aolMeasureZrespmat ${rmamplum} ${rmdelays} ${rmnbfr}" C-m
menucontrolloop_default="zrespoff"
state="menuconfigureloop"
;;
	zrespoff)
zrespstat="OFF"
echo "OFF" > ./status/stat_zresp.txt
tmux kill-session -t zresp
menucontrolloop_default="zresp_on"
state="menuconfigureloop"
;;



	wfsM)
exec 3>&1;
wfsmaskfname=$(dialog --title "Select WFS pixel mask file name" --stdout  --fselect "${wfsmaskfname}" $nbwlines $nbwcols)
echo "$wfsmaskfname" > ./conf/conf_wfsmask_fname.txt
ReadWFSmaskfname
menucontrolloop_default="wfsM"
state="menuconfigureloop"
;;
	dmM)
exec 3>&1;
dmmaskfname=$(dialog --title "Select DM act mask file name" --stdout --fselect "${dmmaskfname}" $nbwlines $nbwcols)
echo "$dmmaskfname" > ./conf/conf_dmmask_fname.txt
ReadDMmaskfname
menucontrolloop_default="dmM"
state="menuconfigureloop"
;;
	wfsref)
exec 3>&1;
wfsreffname=$(dialog --title "Select WFS reference file name" --stdout --fselect "${wfsreffname}" $nbwlines $nbwcols)
echo "$wfsreffname" > ./conf/conf_wfsref_fname.txt
ReadWFSreffname
menucontrolloop_default="wfsref"
state="menuconfigureloop"
;;
	awfsref_on)
acquwfsrefstat=" ON"
echo " ON" > ./status/stat_acquwfsref.txt
tmux new-session -d -s awfsref
#tmux send-keys -t adark "./aol" C-m
menucontrolloop_default="awfsrefoff"
state="menuconfigureloop"
;;
	awfsrefoff)
acquwfsrefstat="OFF"
echo "OFF" > ./status/stat_acquwfsref.txt
tmux kill-session -t awfsref
menucontrolloop_default="awfsref_on"
state="menuconfigureloop"
;;

	mkModes)
menucontrolloop_default="mkModes"
state="menu_mkFModes"
;;
	DMmodes)
DMmodes=$(dialog --title "Select DM Control Modes" --stdout --title "Select DM Control Modes" --fselect ./conf/Cmodes/ $nbwlines $nbwcols)
echo "$DMmodes" > ./conf/conf_DMmodes_name.txt
ReadDMmodesname
menucontrolloop_default="DMmodes"
state="menuconfigureloop"
#state="menu_selectCModes"
;;
	RM)
exec 3>&1;
respM=$(dialog --inputbox "Response Matrix" 0 0 "$respM" 2>&1 1>&3);
exec 3>&-;
echo "$respM" > ./conf/conf_respM_name.txt
ReadrespMname
menucontrolloop_default="RM"
state="menuconfigureloop"
;;

   	 c) 
menucontrolloop_default="c"
CheckLoopConfiguration
state="menuconfigureloop"
;;   


	esac;;
   1) state="menutop";;   
   2) state="menuexit";;
   255) state="menuexit";;
esac


fi








# =====================================================
# ======== Make Fourier Modes  ========================
# =====================================================

if [ $state = "menu_mkFModes" ]; then
stateok=1
menuname=" CONFIGURATION - Make Fourier based Modes"

menuitems=()
menuitems+=( "00.2" "0.2 CPA (Tip/Tilt only)" )
menuitems+=( "00.3" "0.3 CPA (Tip/Tilt + Focus)" )
menuitems+=( "00.5" "0.5 CPA (Tip/Tilt + Focus + AST)" )
for i in `seq 20 40 240 `;
        do
str0=$( echo $i|awk '{printf("%04.1f", $1*0.1)}')
str1=$( echo $i|awk '{printf("%4.1f CPA", $1*0.1)}')
menuitems+=( "$str0" "$str1" )
done 



dialog --title "AO loop configuration" \
--ok-label "Select" \
--cancel-label "Main" \
--help-button --help-label "Exit" \
--default-item ${cpamax} \
--menu "$menuname" \
 50 80 100 "${menuitems[@]}"  2> $tempfile

retval=$?

case $retval in
   0) state="menuconfigureloop"
cpamax=$(cat $tempfile)
echo "$cpamax" > ./conf/conf_cpamax.txt
tmux new-session -d -s aol${LOOPNUMBER}mkmodes
tmux send-keys -t aol${LOOPNUMBER}mkmodes "./aolmkmodes ${cpamax}" C-m
tmux send-keys -t aol${LOOPNUMBER}mkmodes "exit" C-m

;; # button 1:
   1) state="menutop";;  
   2) state="menuexit";; 
   255) state="menuexit";;
esac

fi







# =====================================================
# ======== CONTROL AO LOOP ============================
# =====================================================
if [ $state = "menucontrolloop" ]; then
stateok=1
menuname="CONTROL LOOP"


loopgain=$(echo "$(cat ./conf/conf_loopgain.txt)")
loopmaxlim=$(echo "$(cat ./conf/conf_loopmaxlim.txt)")
loopmultcoeff=$(echo "$(cat ./conf/conf_loopmultcoeff.txt)")


menuitems=( "g" "loop gain    =   ${loopgain}" )
menuitems+=( "m" "loop max lim =   ${loopmaxlim}" )
menuitems+=( "e" "mult coeff   =   ${loopmultcoeff}" )
menuitems+=( "" "" )
menuitems+=( "S" "Start loop processes" )
menuitems+=( "t1" "step 1" )
menuitems+=( "t3" "step 3" )
menuitems+=( "t10" "step 10" )
menuitems+=( "t30" "step 30" )
menuitems+=( "t100" "step 100" )
menuitems+=( "t300" "step 300" )
menuitems+=( "t1000" "step 1000" )
menuitems+=( "N" "LOOP ON" )
menuitems+=( "F" "LOOP OFF" )
menuitems+=( "Z" "LOOP Zero" )
menuitems+=( "K" "Kill LOOP" )
menuitems+=( "" "" )
menuitems+=( "L" "Control Loop" )



state="menutop"


dialog --title "LOOP CONTROL" \
--ok-label "Select" \
--cancel-label "Top" \
--help-button --help-label "Exit" \
--default-item "${menucontrolloop_default}" \
 --menu "$menuname" \
 50 80 100 "${menuitems[@]}"  2> $tempfile

retval=$?
choiceval=$(cat $tempfile)

case $retval in
   0) # button
	case $choiceval in
  	 g) 
menucontrolloop_default="g"
state="menucontrolloop_setgain"
;; 
   	 m)   	
menucontrolloop_default="m"
state="menucontrolloop_setmaxlim"
;;  
   	 e) 
menucontrolloop_default="e"
state="menucontrolloop_setmult"
;;   
   	 S)
rm aolctr-${LOOPNUMBER}-fifo

tmux new-session -d -s aol${LOOPNUMBER}-ctr
tmux send-keys -t aol${LOOPNUMBER}-ctr "ls" C-m
#$xtermopt -e numactl --cpunodebind=$NUMAnode --membind=$NUMAnode ./aolctr &
sleep 1
#xterm $xtermopt -e numactl --cpunodebind=$NUMAnode --membind=$NUMAnode ./aolrun &
#sleep 1
#echo "aolon" >> aolctr-${LOOPNUMBER}-fifo
#sleep 5
#echo "aoloff" >> aolctr-${LOOPNUMBER}-fifo
#sleep 1
menucontrolloop_default="S"
state="menucontrolloop"
;; 
   	 t1)
echo "aolstep 1" >> aolctr-${LOOPNUMBER}-fifo
menucontrolloop_default="t1"
state="menucontrolloop"
;;   
   	 t3)
echo "aolstep 3" >> aolctr-${LOOPNUMBER}-fifo
menucontrolloop_default="t3"
state="menucontrolloop"
;;   
   	 t10)
echo "aolstep 10" >> aolctr-${LOOPNUMBER}-fifo
menucontrolloop_default="t10"
state="menucontrolloop"
;;   
   	 t30)
echo "aolstep 30" >> aolctr-${LOOPNUMBER}-fifo
menucontrolloop_default="t30"
state="menucontrolloop"
;;   
   	 t100)
echo "aolstep 100" >> aolctr-${LOOPNUMBER}-fifo
menucontrolloop_default="t100"
state="menucontrolloop"
;;   
   	 t300)
echo "aolstep 300" >> aolctr-${LOOPNUMBER}-fifo
menucontrolloop_default="t300"
state="menucontrolloop"
;;   
   	 t1000)
echo "aolstep 1000" >> aolctr-${LOOPNUMBER}-fifo
menucontrolloop_default="t1000"
state="menucontrolloop"
;;   
   	 N)
echo "aolon" >> aolctr-${LOOPNUMBER}-fifo
menucontrolloop_default="N"
state="menucontrolloop"
;; 
   	 F)
echo "aoloff" >> aolctr-${LOOPNUMBER}-fifo
menucontrolloop_default="F"
state="menucontrolloop"
;; 
   	 Z)
echo "imzero aol${LOOPNUMBER}_DMmode_cmd" >> aolctr-${LOOPNUMBER}-fifo
echo "readshmim aol${LOOPNUMBER}_dmC" >> aolctr-${LOOPNUMBER}-fifo
echo "imzero aol${LOOPNUMBER}_dmC" >> aolctr-${LOOPNUMBER}-fifo
menucontrolloop_default="Z"
state="menucontrolloop"
;;
   	 K)
ocamstopacq
sleep 1
echo "aoloff" >> aolctr-${LOOPNUMBER}-fifo
echo "aolkill" >> aolctr-${LOOPNUMBER}-fifo
echo "exit" >> aolctr-${LOOPNUMBER}-fifo
sleep 1
ocamstartacq
menucontrolloop_default="K"
state="menucontrolloop"
;;
  	 C) state="menuconfmain";; 
   	 W) state="menucamera";;  
   	 L) state="menucontrolloop";;   
   	 A) state="menualign";;  
	esac;;
   1) state="menutop";;   
   2) state="menuexit";;
   255) state="menuexit";;
esac


fi











#  TEST MODE
if [ $state = "menutestmode" ]; then
stateok=1

testloopstatus="OFF"

file="./status/testloopstatus.txt"
if [ -a $file ]
	then
	testloopstatus=$(echo "$(cat $file)")
	else
	testloopstatus="OFF"
fi



menuname="TEST MODE [${testloopstatus}] - LOOP ${LOOPNUMBER}"



menuitems=( "H" "help" )
menuitems+=( "-" " " )
menuitems+=( "dms" "[${testdmsize}] test mode DM size" )
menuitems+=( "-" " " )
menuitems+=( "Start" "Start test mode" )
menuitems+=( "Stop" "Stop test mode" )
menuitems+=( "-" " " )
menuitems+=( "DMton" "DM turbulence ON" )
menuitems+=( "DMtoff" "DM turbulence OFF" )
menuitems+=( "DMtamp" "DM turbulence amplitude = ${dmturbampl} um" )
menuitems+=( "DMttint" "DM turbulence interval = ${dmturbtint} us" )
menuitems+=( "dm1v" "View DM chan 1 (turbulence) stream" )
menuitems+=( "dm1m" "Monitor DM chan 1 (turbulence) stream" )



dialog --title "TEST MODE" \
--ok-label "Select" \
--cancel-label "Top" \
--help-button --help-label "Exit" \
--default-item "${menutestmode_default}" \
 --menu "$menuname" \
 50 80 100 "${menuitems[@]}"  2> $tempfile

retval=$?
choiceval=$(cat $tempfile)

case $retval in
   0) # button
	case $choiceval in
   	 H)
dialog --title "Help" --msgbox 'Simulation mode\n
\n
Creates shared memory arrays: \n
   aosimdmctrl   : DM control map\n
   WFturb        : Wavefront phase turbulence (512x512)\n
   aosimpsfout   : output PSF (intensity)\n
   aosimwfsim    : output WFS image (intensity)\n
\n
Recomputes aosimpsfout when either aosimdmctrl or WFturb changes' 40 80
menutestmode_default="H"
;;
	dms)
exec 3>&1;testdmsize=$(dialog --inputbox "test mode DM size" 0 0 "$testdmsize" 2>&1 1>&3);
exec 3>&-;
echo "$testdmsize" > ./conf/conf_testdmsize.txt
ReadTestDMsize
menutestmode_default="dms"
state="menutestmode"
;;
   	 Start)
if [ $testloopstatus = "OFF" ]; then
TestModeStart
fi
menutestmode_default="Start"
state="menutestmode"
;;   
   	 Stop) 
if [ $testloopstatus = "ON" ]; then
TestModeStop
fi
menutestmode_default="Stop"
state="menutestmode"
;;  
	DMton)
TestStartTurb
menutestmode_default="DMton"
state="menutestmode"
;;
	DMtoff)
TestStopTurb
menutestmode_default="DMtoff"
state="menutestmode"
;;
	DMtamp)
exec 3>&1;dmturbampl=$(dialog --inputbox "DM turbulence amplitude [um]" 0 0 "$dmturbampl" 2>&1 1>&3);
exec 3>&-;
echo "$dmturbampl" > ./conf/conf_dmturbampl.txt
ReadDMturbampl
menutestmode_default="DMtamp"
state="menutestmode"
;;
	DMttint)
exec 3>&1;dmturbtint=$(dialog --inputbox "DM turbulence interval [us]" 0 0 "$dmturbtint" 2>&1 1>&3);
exec 3>&-;
echo "$dmturbtint" > ./conf/conf_dmturbtint.txt
ReadDMturbtint
menutestmode_default="DMttint"
state="menutestmode"
;;


	dm1v)
$shmimviewexec /tmp/aosimdmctrl1.im.shm 4 &> /dev/null &
menutestmode_default="dm1v"
state="menutestmode"
;;   
	dm1m)
$shmimmonexec aosimdmctrl1
menutestmode_default="dm1m"
state="menutestmode"
;;   

	esac;;
   1) state="menutop";;   
  2) state="menuexit";;
   255) state="menuexit";;
esac

fi











#  VIEW MODE
if [ $state = "menuview" ]; then
stateok=1



menuname="VIEW MODE - LOOP ${LOOPNUMBER}"



menuitems=( "H" "help" )
menuitems+=( "-" " " )
menuitems+=( "wfsv" "View wavefront sensor image stream      (aol${LOOPNUMBER}_wfsim)" )
menuitems+=( "wfsm" "monitor wavefront sensor image stream   (aol${LOOPNUMBER}_wfsim)" )
menuitems+=( "-" " " )
menuitems+=( "dmcv" "View DM control stream" )
menuitems+=( "dmcm" "Monitor DM control stream" )
menuitems+=( "-" " " )



dialog --title "TEST MODE" \
--ok-label "Select" \
--cancel-label "Top" \
--help-button --help-label "Exit" \
--default-item "${menutestmode_default}" \
 --menu "$menuname" \
 50 80 100 "${menuitems[@]}"  2> $tempfile

retval=$?
choiceval=$(cat $tempfile)

case $retval in
   0) # button
	case $choiceval in
   	 H)
dialog --title "Help" --msgbox 'View shared memory streams / monitor loop\n
\n
executable to view shared memory streams: $shmimviewexec\n
' 40 80
menutestmode_default="H"
;;

   	 wfsv)
$shmimviewexec /tmp/aol${LOOPNUMBER}_wfsim.im.shm &> /dev/null &
menutestmode_default="wfsv"
state="menuview"
;;   
   	 wfsm)
$shmimmonexec aol${LOOPNUMBER}_wfsim
menutestmode_default="wfsm"
state="menuview"
;;
   
	dmcv)
$shmimviewexec /tmp/aol${LOOPNUMBER}_dmC.im.shm 4 &> /dev/null &
menutestmode_default="dmcm"
state="menuview"
;;   
	dmcm)
$shmimmonexec aol${LOOPNUMBER}_dmC
menutestmode_default="dmcm"
state="menuview"
;;   

   	 Stop) 
if [ $testloopstatus = "ON" ]; then
TestModeStop
menutestmode_default="Stop"
fi
state="menutestmode"
;;  
	esac;;
   1) state="menutop";;   
  2) state="menuexit";;
   255) state="menuexit";;
esac

fi






















#  SET CONTROL LOOP GAIN
if [ $state = "menucontrolloop_setgain" ]; then
stateok=1
menuname="SET LOOP GAIN - LOOP ${LOOPNUMBER}"

ReadLoopGain


loopgain3=$(echo "scale=0; $loopgain*1000/1" | bc -q 2>/dev/null |awk '{printf("%03d", $1)}')

menuitems=()
menuitems+=( "000" "0.000" )
menuitems+=( "001" "0.001" )
menuitems+=( "005" "0.005" )
menuitems+=( "010" "0.010" )
for i in `seq 50 50 950 `;
        do
str0=$( echo $i|awk '{printf("%03d",$1)}')
str1=$( echo $i|awk '{printf("%5.3f", $1*0.001)}')
menuitems+=( "$str0" "$str1" )
done 


dialog --title "Control loop gain" \
--ok-label "Select" \
--cancel-label "Cancel" \
--help-button --help-label "Exit" \
--default-item ${loopgain3} \
--menu "$menuname" \
 50 80 100 "${menuitems[@]}"  2> $tempfile


retval=$?

case $retval in
   0) state="menucontrolloop"
loopgain=$(cat $tempfile|awk '{printf("%5.3f", $1*0.001)}')
echo "$loopgain" > ./conf/conf_loopgain.txt
echo "aolsetgain ${loopgain}" >> aolctr-${LOOPNUMBER}-fifo
;; # button 1:
   1) state="menucontrolloop";; 
   2) state="menuexit";; 
   255) state="menuexit";;
esac


fi










#  SET CONTROL LOOP MAX LIM
if [ $state = "menucontrolloop_setmaxlim" ]; then
stateok=1
menuname="SET LOOP MAX LIMIT - LOOP ${LOOPNUMBER}"

ReadLoopMaxLim

loopmaxlim3=$(echo "scale=0; $loopmaxlim*1000/1" | bc -q 2>/dev/null |awk '{printf("%03d", $1)}')

menuitems=()
menuitems+=( "000" "0.000" )
menuitems+=( "001" "0.001" )
menuitems+=( "005" "0.005" )
menuitems+=( "010" "0.010" )
for i in `seq 50 50 950 `;
        do
str0=$( echo $i|awk '{printf("%03d",$1)}')
str1=$( echo $i|awk '{printf("%5.3f", $1*0.001)}')
menuitems+=( "$str0" "$str1" )
done 



dialog --title "Control loop max limit" \
--ok-label "Select" \
--cancel-label "Cancel" \
--help-button --help-label "Exit" \
--default-item ${loopmaxlim3} \
--menu "$menuname" \
 50 80 100 "${menuitems[@]}"  2> $tempfile

retval=$?

case $retval in
   0) state="menucontrolloop"
loopmaxlim=$(cat $tempfile|awk '{printf("%5.3f", $1*0.001)}')
echo "$loopmaxlim" > ./conf/conf_loopmaxlim.txt
echo "aolsetmaxlim ${loopmaxlim}" >> aolctr-${LOOPNUMBER}-fifo
;; # button 1:
   1) state="menucontrolloop";; 
   2) state="menuexit";; 
   255) state="menuexit";;
esac

fi





#  SET MULT COEFF
if [ $state = "menucontrolloop_setmult" ]; then
stateok=1
menuname="SET LOOP MULT COEFF - LOOP ${LOOPNUMBER}"

ReadLoopMultCoeff

loopmultcoeff3=$(echo "scale=0; $loopmultcoeff*1000/1" | bc -q 2>/dev/null |awk '{printf("%03d", $1)}')

menuitems=()
for i in `seq 000 100 800 `;
        do
str0=$( echo $i|awk '{printf("%03d",$1)}')
str1=$( echo $i|awk '{printf("%5.3f", $1*0.001)}')
menuitems+=( "$str0" "$str1" )
done 
menuitems+=( "" "" )
for i in `seq 900 10 980 `;
        do
str0=$( echo $i|awk '{printf("%03d",$1)}')
str1=$( echo $i|awk '{printf("%5.3f", $1*0.001)}')
menuitems+=( "$str0" "$str1" )
done 
menuitems+=( "" "" )
for i in `seq 990 1 999 `;
        do
str0=$( echo $i|awk '{printf("%03d",$1)}')
str1=$( echo $i|awk '{printf("%5.3f", $1*0.001)}')
menuitems+=( "$str0" "$str1" )
done 
menuitems+=( "" "" )
menuitems+=( "1000" "1.000" )


dialog --title "Control loop mult coeff" \
--ok-label "Select" \
--cancel-label "Cancel" \
--help-button --help-label "Exit" \
--default-item ${loopmultcoeff3} \
--menu "$menuname" \
 50 80 100 "${menuitems[@]}"  2> $tempfile

retval=$?

case $retval in
   0) state="menucontrolloop"
loopmultcoeff=$(cat $tempfile|awk '{printf("%5.3f", $1*0.001)}')
echo "$loopmultcoeff" > ./conf/conf_loopmultcoeff.txt
echo "aolsetmult ${loopmultcoeff}" >> aolctr-${LOOPNUMBER}-fifo
;; # button 1:
   1) state="menucontrolloop";; 
   2) state="menuexit";; 
   255) state="menuexit";;
esac

fi














if [ $state = "menuexit" ]; then
stateok=1
echo "exit"
exit
fi



if [ $stateok = 0 ]; then
echo "state \"$state\" not recognized ... exit"
exit
fi


done
















