#!/bin/bash


########################################################
# StreamLink
#
# Creates link to existing stream
#
# Argument:
#   stream      link name (full name: aol<loop>_<stream>)
#
#
# The stream to which the link will point is in:
# ./conf/streamlink_<stream>.name.txt
#
# Example:
# echo "ocam2d" > conf/streamlink_wfsim.name.txt
# StreamLink ocam2d wfsim
# 
# links aol<loopnb>_wfsim to ocam2d stream
# If conf file doesn't exist, attempts to link
# to <stream>
########################################################




execname="./AOloopControl"

file="./conf/streamlink_$1.name.txt"
if [ -a $file ]; then

# READ LOOP NUMBER
if [ -f LOOPNUMBER ]; then
LOOPNUMBER=$( cat LOOPNUMBER )
else
LOOPNUMBER="7"
fi

	streamname=$( cat $file )
	rm /tmp/aol${LOOPNUMBER}_$1.im.shm
	ln -s /tmp/${streamname}.im.shm /tmp/aol${LOOPNUMBER}_$1.im.shm


./AOloopControl << EOF
readshmim aol${LOOPNUMBER}_$1
readshmimsize aol${LOOPNUMBER}_$1 "./conf/streamlink_$1.imsize.txt"
exitCLI
EOF

fi

