#!/bin/bash

# set processes affinities


# low latency TCP

sudo ethtool -C eth2 rx-usecs 0
sudo ethtool -C eth4 rx-usecs 0
sudo ethtool -C eth2 tx-usecs 0
sudo ethtool -C eth4 tx-usecs 0

sudo ethtool -A eth2 autoneg off rx off tx off
sudo ethtool -A eth4 autoneg off rx off tx off

sudo /sbin/sysctl -w net.ipv4.tcp_low_latency=1
sudo /sbin/sysctl -w net.ipv4.tcp_sack=0
sudo /sbin/sysctl -w net.ipv4.tcp_timestamps=0
sudo /sbin/sysctl -w net.ipv4.tcp_fastopen=1




# TURN OFF HYPERTHREADING
echo "Turn off hyperthreading"
sudo -s << EOF
echo 1 > /sys/devices/system/cpu/cpu0/online
echo 1 > /sys/devices/system/cpu/cpu1/online
echo 1 > /sys/devices/system/cpu/cpu2/online
echo 1 > /sys/devices/system/cpu/cpu3/online
echo 1 > /sys/devices/system/cpu/cpu4/online
echo 1 > /sys/devices/system/cpu/cpu5/online
echo 1 > /sys/devices/system/cpu/cpu6/online
echo 1 > /sys/devices/system/cpu/cpu7/online
echo 1 > /sys/devices/system/cpu/cpu8/online
echo 1 > /sys/devices/system/cpu/cpu9/online
echo 1 > /sys/devices/system/cpu/cpu10/online
echo 1 > /sys/devices/system/cpu/cpu11/online
echo 1 > /sys/devices/system/cpu/cpu12/online
echo 1 > /sys/devices/system/cpu/cpu13/online
echo 1 > /sys/devices/system/cpu/cpu14/online
echo 1 > /sys/devices/system/cpu/cpu15/online
echo 1 > /sys/devices/system/cpu/cpu16/online
echo 1 > /sys/devices/system/cpu/cpu17/online
echo 1 > /sys/devices/system/cpu/cpu18/online
echo 1 > /sys/devices/system/cpu/cpu19/online
echo 1 > /sys/devices/system/cpu/cpu20/online
echo 1 > /sys/devices/system/cpu/cpu21/online
echo 1 > /sys/devices/system/cpu/cpu22/online
echo 1 > /sys/devices/system/cpu/cpu23/online
echo 1 > /sys/devices/system/cpu/cpu24/online
echo 1 > /sys/devices/system/cpu/cpu25/online
echo 1 > /sys/devices/system/cpu/cpu26/online
echo 1 > /sys/devices/system/cpu/cpu27/online

echo 0 > /sys/devices/system/cpu/cpu28/online
echo 0 > /sys/devices/system/cpu/cpu29/online
echo 0 > /sys/devices/system/cpu/cpu30/online
echo 0 > /sys/devices/system/cpu/cpu31/online
echo 0 > /sys/devices/system/cpu/cpu32/online
echo 0 > /sys/devices/system/cpu/cpu33/online
echo 0 > /sys/devices/system/cpu/cpu34/online
echo 0 > /sys/devices/system/cpu/cpu35/online
echo 0 > /sys/devices/system/cpu/cpu36/online
echo 0 > /sys/devices/system/cpu/cpu37/online
echo 0 > /sys/devices/system/cpu/cpu38/online
echo 0 > /sys/devices/system/cpu/cpu39/online
echo 0 > /sys/devices/system/cpu/cpu40/online
echo 0 > /sys/devices/system/cpu/cpu41/online
echo 0 > /sys/devices/system/cpu/cpu42/online
echo 0 > /sys/devices/system/cpu/cpu43/online
echo 0 > /sys/devices/system/cpu/cpu44/online
echo 0 > /sys/devices/system/cpu/cpu45/online
echo 0 > /sys/devices/system/cpu/cpu46/online
echo 0 > /sys/devices/system/cpu/cpu47/online
echo 0 > /sys/devices/system/cpu/cpu48/online
echo 0 > /sys/devices/system/cpu/cpu49/online
echo 0 > /sys/devices/system/cpu/cpu50/online
echo 0 > /sys/devices/system/cpu/cpu51/online
echo 0 > /sys/devices/system/cpu/cpu52/online
echo 0 > /sys/devices/system/cpu/cpu53/online
echo 0 > /sys/devices/system/cpu/cpu54/online
echo 0 > /sys/devices/system/cpu/cpu55/online
exit
EOF




# SYSTEM ARCHITECTURE, CPU SETS

# ================ CPU 0 ====================
# cores: 0 2 4 6 8 10 12 14 16 18 20 22 24 26

# system        non real-time processes                 2 4 6 8 10 12 14 16 18 20 22
# dmcomb        DM combine channels                     24
# dmdrv         MEMs DM driver                          26

# ================ CPU 1 ===================
# cores: 1 3 5 7 9 11 13 15 17 19 21 23 25 27

# aolRT         real-time loop computation              3 5 7 9 11 13 15 17 19
# aolRT1        modal extraction (WFS output)           21
# aolRT2        modal processing (DM contr. channel)    23
# aolCOM        WFS camera communication                25
# ocamdec       ocam image decoding                     27                                                                                                       
  

sudo cset set --cpu 0,1,2,4,6,8,10,12,14,16,18,20 --set system
sudo cset set --cpu 22 --set LQG
sudo cset set --cpu 24 --cpu_exclusive --set dmcomb
sudo cset set --cpu 26 --cpu_exclusive --set dmdrv

sudo cset set --cpu 3,5,7,9,11,13,15,17 --cpu_exclusive --set aolRT
sudo cset set --cpu 19 --cpu_exclusive --set aolRT1
sudo cset set --cpu 21 --cpu_exclusive --set aolRT2
sudo cset set --cpu 23,25 --cpu_exclusive --set aolCOM
sudo cset set --cpu 27 --cpu_exclusive --set ocamdec


# move as much as possible to system
sudo cset proc -m -f root -t system
sudo cset proc -k -f root -t system


pidlist=$( pgrep aolrun|xargs echo | sed 's/ /,/g' )
sudo cset proc -m -p $pidlist -t aolRT


pidlist=$( pgrep TCP|xargs echo | sed 's/ /,/g' )
sudo cset proc -m -p $pidlist -t aolCOM

pidlist=$( pgrep dmcomb|xargs echo | sed 's/ /,/g' )
sudo cset proc -m -p $pidlist -t dmcomb

pidlist=$( pgrep ocam|xargs echo | sed 's/ /,/g' )
sudo cset proc -m -p $pidlist -t ocamdec

pidlist=$( pgrep bmc|xargs echo | sed 's/ /,/g' )
sudo cset proc -m -p $pidlist -t dmdrv


pidlist=$( pgrep modeval|xargs echo | sed 's/ /,/g' )
sudo cset proc -m -p $pidlist -t aolRT1



tmux new-session -d -s cpulatency
tmux send-keys -t cpulatency "sudo /home/scexao/bin/setlatency 0" C-m



# show CPU sets
cset set -l



# set precision timing protocol

ssh scexao@scexao2 "tmux new-session -d -s ptp" 
ssh scexao@scexao2 "tmux send-keys -t ptp \"ls\" C-m"



touch cpuconfigOK
